### ISSUE TITLE
in crates.io the version remains 1.4.2

### ISSUE THREAD

**Issue by iotoi8cn** [Byron/termbook#4]
https://crates.io/search?q=termbook

**Comment by Byron** [comment]
<img width="951" alt="Screenshot 2020-11-27 at 19 04 48" src="https://user-images.githubusercontent.com/63622/100442770-8b6fc700-30e3-11eb-9004-00ac149805de.png">

 Maybe a misunderstanding. The CLI is 1.4.6, which uses a library crate at 1.4.2.

I wouldn't expect this to be an issue but am happy to learn if that's not true.
